name: quizz_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  google_sign_in: ^5.4.0
  formz: ^0.4.1
  font_awesome_flutter: ^10.1.0
  flow_builder: ^0.0.9
  flutter_spinkit: ^5.1.0
  json_annotation: ^4.6.0
  dio: ^4.0.6
  antdesign_icons: ^0.0.3
  percent_indicator: ^4.2.2
  material_design_icons_flutter: ^5.0.6996

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:

 assets:
    - assets/

